<?php
/**
 * Created by PhpStorm.
 * User: Yachitha Sandaruwan
 * Date: 12/9/2018
 * Time: 11:27 PM
 */

namespace App\Http\Controllers\Expenses\SalesRepExpense;


use App\Http\Controllers\Expenses\ExpenseController;

class SalesRepExpenseController extends ExpenseController
{
    function filterRecords ()
    {
        parent::filterRecords (); // TODO: Change the autogenerated stub
    }

}
