<?php
/**
 * Created by PhpStorm.
 * User: Yachitha Sandaruwan
 * Date: 12/9/2018
 * Time: 11:26 PM
 */

namespace App\Http\Controllers\Expenses\OtherExpense;


use App\Http\Controllers\Expenses\ExpenseController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class OtherExpenseController extends ExpenseController
{
    function filterRecords ()
    {
        parent::filterRecords (); // TODO: Change the autogenerated stub
    }

    public function createOtherExpenses(Request $request) {
        $validate = Validator::make($request->all (),[
            'description'=>'required|string|max:255',
            'amount'=>'required|regex:/[0-9]/'
        ]);
    }
}
